id: PE996E0A3
initial_creation_type: input
source_metadata:
  title: Mipham Rinpoche Series
  language: bo
  description: 'Texts by and about the great Nyingma polymath Jamgön Mipham Namgyal
    Gyatso (mi pham rnam rgyal rgya mtsho, 1846-1912), arguably the most influential
    Tibetan scholar of recent times:'
  volume:
    37b5716cc38849b99f23cdabe69f6507:
      title: Advice for Beginners
      parent: Advice
    4ea72add1a054f3bb813e5866f844d30:
      title: Advice to Jigme Tenpe Nyima
      parent: Advice
    02a480ba35c649cab0fdeb8489cdefe3:
      title: Essence of the 84000 Approaches to the Dharma
      parent: Advice
    b43cad44ed3645e19c9bae058b004102:
      title: How to Cultivate Concentration
      parent: Advice
    29d184e1ecfa45ccaece51f19e61745b:
      title: Profound Instruction on Śamatha
      parent: Advice
    e17157d743b3466786c5c487501a9f41:
      title: Satirical Advice for the Four Schools
      parent: Advice
    b69f15168bd047cd90c83bb5aeef6137:
      title: The Four Dharma Traditions of Tibet
      parent: Advice
    bbc8664d2652477ea18a10ed801b88fe:
      title: The Mahāmudrā Practice of Stillness, Movement and Awareness
      parent: Advice
    1b3d12bbb4db4dc5b9e116bd2e7f8156:
      title: The Perfect Equality of the Dharmadhātu
      parent: Advice
    aa531ce9b47d4d33b6dff037c1fd2058:
      title: A Brief Prayer for Summoning Prosperity
      parent: Aspiration Prayers
    8fea3b5426104e559b3d59d4f2d60dd0:
      title: Aspiration for the Four Activities
      parent: Aspiration Prayers
    ea7375a0cb7543d8a758180291c9b443:
      title: Light Offering Prayer
      parent: Aspiration Prayers
    c75633f0d0454124a70747ce469373d5:
      title: Sukhāvatī Aspiration
      parent: Aspiration Prayers
    a74a38c230b84897b91dbc073a7c8f85:
      title: Summoning the Spirit of Abundance - The Hook of Divine Substance
      parent: Aspiration Prayers
    b7c461de209745afb2f8ebb827a5c852:
      title: 'The Secret Path of Wisdom: A Prayer of Aspiration for the Mountain of
        Glory'
      parent: Aspiration Prayers
    7a96da169026436888a7d466ed074113:
      title: Verses of the Eight Noble Auspicious Ones
      parent: Aspiration Prayers
    fa7d8e0a30b1438184359d607eaf6c2b:
      title: 'Words to Delight the Sovereigns of the Dharma: A Prayer of Aspiration
        for the Flourishing and Spread of the Ancient Translation Tradition'
      parent: Aspiration Prayers
    910f09c572114bb0a183e6ef1791ec9d:
      title: A Brief Version of the 'Chinese' Practice of Averting Periodic Obstacles
      parent: Averting Obstacles
    cfd1f9fb00224df4b6f941e22c1c3c86:
      title: Benedictory Verses for A Brilliant Elucidation of Logical Reasoning
      parent: Benedictory Verses
    03ccb08a02ef476392cdd6118ad8e1ff:
      title: Benedictory Verses for White Lotus
      parent: Benedictory Verses
    9889064bee12499a8ccdafb63c62162d:
      title: Ascertaining the Two Kinds of Selflessness
      parent: Buddhist Philosophy
    a9c633a65a804a2288f127783b0f785a:
      title: 'Gateway to Learning: Four Great Logical Arguments of the Middle Way'
      parent: Buddhist Philosophy
    a019b8fc49eb48f0bee95352aeb9c8c4:
      title: 'Gateway to Learning: Individual Selflessness'
      parent: Buddhist Philosophy
    778722569c9945258f7609bb4dcca625:
      title: Profound Instruction on the View of the Middle Way
      parent: Buddhist Philosophy
    23699865910b44cc8b6d8ea38495576e:
      title: Putting the Instruction on the Purification of Mental Activity into Practice
      parent: Buddhist Philosophy
    835843c6376c4d04ae89208310f9af20:
      title: The Sword of Wisdom for Thoroughly Ascertaining Reality
      parent: Buddhist Philosophy
    1cccd572bfe04153b657669cde332188:
      title: 'The Vajra Mirror: Cutting through Doubts Concerning Self-Awareness'
      parent: Buddhist Philosophy
    fd9235c99bb74210b08b65c627638dac:
      title: The Wheel of Analytical Meditation That Thoroughly Purifies Mental Activity
      parent: Buddhist Philosophy
    3335a6bfd2f54b9d8930a8becf089d8d:
      title: Brief Offering Prayer to Durtrö Lhamo, Mistress of the Charnel Ground
      parent: Dharma Protectors
    afa75d3ba36242079ad3cf7874b8e5f2:
      title: Brief Offering Prayer to Ekajaṭī
      parent: Dharma Protectors
    08269bc058554cb0912e5a08ab2e60db:
      title: Brief Offering Prayer to Tsiu Marpo
      parent: Dharma Protectors
    ad1a1ad2e2784526968f001e50531e12:
      title: Brief Offering Prayer to Za Rāhula
      parent: Dharma Protectors
    540ea32474314d29b435e24cdc45f86c:
      title: Brief Offering Prayer to the Oath-Bound Vajrasādhu
      parent: Dharma Protectors
    42ad39296e7342a0b5a8ab0f94f4a6c2:
      title: Offering to the Five Medicine Sisters, Guardians of the Earth
      parent: Dharma Protectors
    54da1afba4b14fd18d8991e5e9baf400:
      title: 'A Lamp to Dispel Darkness: An Instruction that Points Directly to the
        Very Essence of Mind in the Tradition of ‘the Old Realized Ones’'
      parent: Dzogchen
    00c2a5463254410d9882676c7168158f:
      title: Pith Instruction on the Three Crucial Statements
      parent: Dzogchen
    b509219d2da147f481c38924bc9b5d91:
      title: 'Self-Radiance of Indestructible Awareness and Emptiness: An Aspiration
        towards the Meaning of the Indivisible Ground, Path and Fruition of the Great
        Perfection Mañjuśrī'
      parent: Dzogchen
    58455579dce84528986c934a810b7887:
      title: The Essence of Mind
      parent: Dzogchen
    a9a623c413ee4069a6651e78051b9540:
      title: 'The Essence of Wisdom: How to Sustain the Face of Rigpa'
      parent: Dzogchen
    a81f4a434b294b6cb08d396e1e7256f6:
      title: The Key Points of Trekchö
      parent: Dzogchen
    54b630a0cd4d44ba9e19044841d2deab:
      title: The Nature of Mind
      parent: Dzogchen
    af308887d8ff4f27ad0f4c67b5bef31e:
      title: Brief Gesar Windhorse Invocation
      parent: Gesar
    63932c593c514ac9aab69d5aa3dc169c:
      title: Brief Offering Prayer to Gesar
      parent: Gesar
    25eea40946f841d4884df619473892a5:
      title: Great Clouds of First-Portion Offerings for Prosperity
      parent: Gesar
    4d919c06b9484d02a985cec4270b6826:
      title: Prayer to Gesar
      parent: Gesar
    b12fdf030b794aa0a843521c8ef04708:
      title: Short Windhorse Prayer to Gesar
      parent: Gesar
    1ed5b8c4670c4e4d9aa69267bacfb1fc:
      title: The Prayer and Offering to 'The Great Lion, Gesar the Jewel', that Spontaneously
        Accomplishes Activities
      parent: Gesar
    b33ca34eca5d4db1a14172ae50ff8c65:
      title: 'The Spontaneous Fulfilment of Wishes: A Daily Prayer to Gesar, King
        of the Dralas'
      parent: Gesar
    5821a6ee841647ea96427d5695d93f97:
      title: The Swift Accomplishment of Enlightened Activity through Invocation and
        Offering
      parent: Gesar
    09f242aca4b9426b9ca1fbc94c466df1:
      title: 'The Swift Fulfilment of Wishes: A Brief Offering Prayer to King Gesar'
      parent: Gesar
    fb25248485d143a7a1dc4326fb610cf3:
      title: 'The Swift Infusion of Blessings: A Guru Yoga of the Great Embodiment
        of Unchanging Awareness Wisdom'
      parent: Gesar
    2fa2e6a27a8f42298d7653780a02b66f:
      title: 'A Shower of Blessings: A Guru Yoga Practice to Accompany the Seven Line
        Prayer (Addendum)'
      parent: Guru Yoga
    9411caf2331849ffb004b1ae648cb4df:
      title: 'A Shower of Blessings: A Guru Yoga Practice to Accompany the Seven-Line
        Prayer'
      parent: Guru Yoga
    78f082b7a0c9440f8d51da1696102289:
      title: 'A Shower of Wisdom: A Guru Yoga of Garab Dorje'
      parent: Guru Yoga
    61b2852a0cf44ced9232949ba8e144b4:
      title: 'Great Treasury of Siddhis: A Guru Yoga of Paṇchen Smṛti'
      parent: Guru Yoga
    73d5bd38a69640b28a9f4f6fb807a2db:
      title: Guru Yoga Focusing upon Noble Kurukullā
      parent: Guru Yoga
    f757465ce1d845c9851837e7ce3eb9cf:
      title: 'Shower of Blessings: A Guru Yoga of the Great Paṇḍita, Glorious Rongzom'
      parent: Guru Yoga
    f40ab04089c94ec09b772eaf6d996906:
      title: 'Swift Infusion of Blessings: A Guru Yoga based on Jamgön Mipham Gyatso'
      parent: Guru Yoga
    1d90462fed4d45b192352963f97c7d5a:
      title: Short Sang Offering to Kurukullā
      parent: Kurukullā
    901abec3a1da45f98d90ae9e819e3193:
      title: Short Torma Offering to Kurukullā
      parent: Kurukullā
    04d35d0abf3142fd9f577b20fd9f4a2d:
      title: 'The Lotus Net: A Sang Offering to the Mighty Lotus Ḍākinī, Kurukullā'
      parent: Kurukullā
    730d574f842f4a61b04a39284a00f320:
      title: Brief Dzogchen Lineage Prayer
      parent: Lineage Prayers
    63b2cb7b06bf446193a6352069f59211:
      title: Prayer to Longchenpa (Adapted from the Words of Mipham Rinpoche)
      parent: Lineage Prayers
    fe18ef69edf84f4a92d8fe274a158034:
      title: 'The Melodious Song of Immortality: A Prayer for Long Life'
      parent: Long Life Prayers
    3a3d46144e11405fb1ebd805206b83f9:
      title: Extemporary Practice of Longevity for Oneself or Others
      parent: Longevity
    d36e82f777c240abae79f2474d1f208c:
      title: Brief Windhorse Invocation
      parent: Lungta
    3b0edfcdb9c14b61a1cce3f3a283ccfe:
      title: Daily Lungta Recitation
      parent: Lungta
    52c24636656946fe93528f78e8737bd3:
      title: The Swift Fulfilment of All Wishes—Offering the Flag of Windhorse
      parent: Lungta
    275b90279ba84ae1a22cff73cf996f99:
      title: The Mantra Collection that Incinerates All the Diseases of this Kaliyuga
      parent: Mantras
    6ea59b3209c44881af970fcb66143353:
      title: Wrathful Guru Mantra Visualization
      parent: Mantras
    888a7fb5504544a1b93fb02c94f08cf8:
      title: 'The Wish-Granting King of Jewels: An Essential Garland of Offerings'
      parent: Offering
    86ab18f1096a43b1b896b66aad2baebe:
      title: 'Beautiful Adornment of the Earth: In Praise of Kṣitigarbha'
      parent: Praise
    7cab25d93e704dfbbbcd31c024d177f2:
      title: 'Gentle Splendour: Praises to the Great Abbot Śāntarakṣita'
      parent: Praise
    f8581e96881041da994d26a3d341d609:
      title: 'Snowy Lands: Praises to the Great Dharma Emperor Tri Songdetsen'
      parent: Praise
    19eb7b08c5d44ff498bd0367f727cc54:
      title: 'The Three Kāyas: Praises to the Great Master Padmasambhava'
      parent: Praise
    fed67ab8c59f420e9b4e6ae462f91595:
      title: Prayer Recalling the Life and Liberation of the Mañjunātha Guru
      parent: Prayers
    8f0fec025b4e418b92505800db9405ed:
      title: Prayer to Akṣobhya
      parent: Prayers
    0fd8d64a6d42466e9c703a9a1cef9581:
      title: Prayer to Smṛtijñānakīrti
      parent: Prayers
    8521836fdb904647bd99be33d6d4a037:
      title: Three Prayers from the Earth Pig Year
      parent: Prayers
    af4551607d7847d7b734770c3d47f7f6:
      title: 'Wangdü: The Great Cloud of Blessings—The Prayer which Magnetizes All
        that Appears and Exists'
      parent: Prayers
    6e778f62d06b4ec7beb2528d0e4c4153:
      title: A Brief Prayer for the Spontaneous Fulfilment of Aspirations
      parent: Prayers to Guru Rinpoche
    f55e08656f5b46ab9ed2ac1b81b5f8de:
      title: Recollecting the Deeds of The Tenth Days
      parent: Prayers to Guru Rinpoche
    26f7e29577054342bcfeb3605fcb382d:
      title: The Prayer which is the Source of All True Realization
      parent: Prayers to Guru Rinpoche
    34ddd9e6b9b7477abfd8d36dbda25e77:
      title: 'In Praise of Mañjuśrī: Increasing Intelligence to the Full'
      parent: Prayers to Mañjuśrī
    ae43ee7dd2b744fc92d8291316edaad8:
      title: 'In Praise of Mañjuśrī: The Great Treasure of Blessings'
      parent: Prayers to Mañjuśrī
    9c37a06be8ec4cf496cdd35e0f6ea09f:
      title: In Praise of the Protector Mañjughoṣa
      parent: Prayers to Mañjuśrī
    415877d70e814680ad4453d06ce35ac7:
      title: Prayer to Mañjuśrī
      parent: Prayers to Mañjuśrī
    00289ba47d16400aa8dc3ba7f3df69d4:
      title: Prayer to the Sovereign of Dharma and Retinue
      parent: Prayers to Śākyamuni
    86d6cc58865048629607b47fedb69087:
      title: 'The Treasury of Blessings: A Practice of Buddha Śākyamuni'
      parent: Prayers to Śākyamuni
    4aacdb47bc7e49958f05c7d6e8005797:
      title: 'Illuminating the Path to Liberation: A Preliminary Practice (Ngöndro)'
      parent: Preliminary Practice
    5963dce82e544213b376c763f52c1038:
      title: A Sādhana of Jambhala
      parent: Sādhanas
    0611755b73d2415ebeab48562f55d12a:
      title: A Sādhana of Kurukullā
      parent: Sādhanas
    022150ec4a3c4bf18c3262d04272c2bb:
      title: A Sādhana of Sitātapatrā
      parent: Sādhanas
    266f15ffb5ad4bdb869318f37ab85fda:
      title: A Sādhana of White Sarasvatī
      parent: Sādhanas
    dfb7890121b34c7e9b72cb82f2e43b4f:
      title: Acala Sādhana
      parent: Sādhanas
    4a17a8cb6fca40528a28581e5b48fb7e:
      title: Kṣitigarbha Visualization and Mantra Recitation
      parent: Sādhanas
    d8b1db7c68cf4642bb0235e7b26fbfb8:
      title: Sādhana of Mārīcī
      parent: Sādhanas
    78c39e3d57044967a8f0c8ef651b7036:
      title: Visualization and Recitation of the Six-Syllable Mantra of Avalokiteśvara
      parent: Sādhanas
    192824cf701446e5a069b2c7b102bfc2:
      title: Brief Sang Offering
      parent: Sang Offering
    85a90dcfbb9c40d4bb6916ecea72b6a6:
      title: Brief Sang Offering to Purify Contamination
      parent: Sang Offering
    5af87b9352b94627ad8bff65889b1d2f:
      title: 'The Glorious Gift of Longevity and Granting All Desires: A Liturgy for
        Saving Lives'
      parent: Saving Lives
    1a58a9ce07ce4b58bbf2d3822891619d:
      title: Five-Verse Doha of Yogic Realization
      parent: Songs
    1b84c09a3e2544e6a7a730bb0267fcfc:
      title: 'Freedom from All Adversity: A Sur Offering to Harmful Influences, Obstacle-Makers
        and Elemental Spirits'
      parent: Sur Offering
    e1133eb5f23b40b7964fb0487a63b03c:
      title: Prayer to Tārā, Combined with Her Mantra
      parent: Tārā
    06823493f38d40f191bc228f9ee056a4:
      title: Outline of the Ten Royal Sūtras
      parent: Topical Outlines
    a8be760a12f04fcdaec8c3a05e594022:
      title: Concise Tsok Feast
      parent: Tsok
    d0f9a73c1b9b439ca067311061ae9d8d:
      title: 'Excellent Vase of Splendour: The Tsok Feast Offering to Accompany the
        Vajra Seven-Line Prayer'
      parent: Tsok
    32febd9abb9b4610b06db94bbab3f860:
      title: A Method of Purifying Samaya Violations by Relying on the Glorious Guru
        Vajrasattva
      parent: Vajrasattva
created_at: '2022-03-01T00:57:12.466804'
last_modified_at: '2022-03-01T00:57:12.466806'
statistics:
  total_words: 55518
  total_non_words: 5519
quality:
  non_words_ratio: 0.1
